import 'models/site_config.dart';

/// Site entries are described compactly so they can be added or removed in one
/// place. Each row feeds [AnimeSiteConfig] generation below.
///
/// Fields: name, homepageUrl, logoUrl, safeCdnDomains.
/// `hideSelectors` defaults to the global list in [site_config.dart]; only
/// providers that need extra selectors define them inline (the [providerConfigs]
/// map below).
class _SiteRow {
  final String name;
  final String homepageUrl;
  final String logoUrl;
  final List<String> safeCdnDomains;
  final List<String> hideSelectors;
  final bool mature;

  const _SiteRow({
    required this.name,
    required this.homepageUrl,
    this.logoUrl = '',
    this.safeCdnDomains = const [],
    this.hideSelectors = const [],
    this.mature = false,
  });

  AnimeSiteConfig toConfig() => AnimeSiteConfig(
        name: name,
        homepageUrl: homepageUrl,
        domain: AnimeSiteConfig.domainFromUrl(homepageUrl),
        logoUrl: logoUrl,
        hideSelectors: hideSelectors,
        safeCdnDomains: safeCdnDomains.isNotEmpty
            ? safeCdnDomains
            : globalSafeCdnDomains,
        mature: mature,
      );
}

/// Compact table of all providers (existing + new from sites.md). Edit this
/// list to add or remove entries; the [defaultSites] list is generated from it.
const List<_SiteRow> _allSites = [
  // ── Already configured providers (keep their tuned selectors/CDNs) ──
  _SiteRow(
    name: 'AnimeX',
    homepageUrl: 'https://animex.one/home',
    logoUrl: 'https://animex.one/_app/immutable/assets/favicon.CdbYna26.png',
    safeCdnDomains: ['cdn.animex.one', 'img.animex.one'],
    hideSelectors: ['header', '.site-header', '#header', 'footer',
        '.site-footer', '#footer', '.home-popup', '.promo-banner',
        '[class*="chat" i]'],
  ),
  _SiteRow(
    name: 'AnimeParadise',
    homepageUrl: 'https://www.animeparadise.moe/',
    logoUrl: 'https://www.animeparadise.moe/icon/apple-touch-icon.png',
    safeCdnDomains: ['cdn.animeparadise.moe', 'static.animeparadise.moe'],
    hideSelectors: ['nav', '.navbar', '.site-footer', '.ads-section',
        '.newsletter-modal', '.popup-overlay'],
  ),
  _SiteRow(
    name: 'AniHQ',
    homepageUrl: 'https://anihq.cc/home/',
    logoUrl: 'https://anihq.cc/apple-touch-icon.png',
    safeCdnDomains: ['vid.anihq.cc', 'cdn.anihq.cc'],
    hideSelectors: ['.top-bar', '.header-wrap', '.footer-wrap',
        '.sidebar-ads', '#live-chat', '.interstitial'],
  ),
  _SiteRow(
    name: 'Animeya',
    homepageUrl: 'https://animeya.cc/home',
    logoUrl: 'https://animeya.cc/apple-icon.png',
    safeCdnDomains: ['media.animeya.cc', 'edge.animeya.cc'],
    hideSelectors: ['header', '.main-header', 'footer', '.main-footer',
        '.ad-container', '.cookie-notice', '.chat-dock'],
  ),
  _SiteRow(
    name: 'AnimeKizz',
    homepageUrl: 'https://animekizz.live/',
    logoUrl: 'https://animekizz.live/logo.ico',
    safeCdnDomains: ['stream.animekizz.live', 'cdn.animekizz.live'],
    hideSelectors: ['.site-nav', '.site-foot', '.popunder', '.banner-ad',
        '.age-gate', '.modal'],
  ),
  _SiteRow(
    name: 'AniWave',
    homepageUrl: 'https://aniwaves.ru/',
    logoUrl: 'https://aniwaves.ru/assets/images/favicons/apple-touch-icon.png',
    safeCdnDomains: ['video.aniwave.com.se', 'cdn.aniwave.com.se'],
    hideSelectors: ['header', '.header', 'footer', '.footer', '.ad-banner',
        '.popup', '.chat-box'],
  ),
  _SiteRow(
    name: 'AnimePahe',
    homepageUrl: 'https://animepahe.pw/',
    logoUrl: 'https://animepahe.ch/wp-content/uploads/2026/04/favicon.png',
    safeCdnDomains: ['cdn.animepahe.pw', 'img.animepahe.pw', 's4.animepahe.pw'],
    hideSelectors: ['.header', '#header', '.footer', '#footer', '.navbar',
        '.ads', '.popup', '.modal'],
  ),
  _SiteRow(
    name: 'ReAnime',
    homepageUrl: 'https://reanime.to/home',
    logoUrl: 'https://reanime.to/apple-touch-icon.png',
    safeCdnDomains: ['cdn.reanime.to', 'img.reanime.to', 'stream.reanime.to'],
    hideSelectors: ['header', '.site-header', 'footer', '.site-footer',
        '.promo-banner', '.popup', '.chat-dock'],
  ),
  _SiteRow(
    name: 'AnimeSalt',
    homepageUrl: 'https://animesalt.link/',
    logoUrl: 'https://animesalt.link/favicon.ico',
    safeCdnDomains: ['cdn.animesalt.link', 'static.animesalt.link'],
    hideSelectors: ['header', '.site-header', 'footer', '.site-footer',
        '.popup', '.modal', '[class*="chat" i]'],
  ),
  _SiteRow(
    name: 'AniChi',
    homepageUrl: 'https://anichi.to/',
    logoUrl: 'https://anichi.to/anichi/images/favicon.png?v=1',
    safeCdnDomains: ['cdn.anichi.to', 'static.anichi.to'],
    hideSelectors: ['header', '.header', 'footer', '.footer', '.popup-overlay',
        '.modal', '[class*="chat" i]'],
  ),
  _SiteRow(
    name: 'AniKage',
    homepageUrl: 'https://anikage.cc/',
    logoUrl: 'https://anikage.cc/favicon.ico',
    safeCdnDomains: ['cdn.anikage.cc', 'stream.anikage.cc'],
    hideSelectors: ['.site-nav', '.site-foot', '.popunder', '.banner-ad',
        '.modal', '[class*="chat" i]'],
  ),
  _SiteRow(
    name: 'AniSuge',
    homepageUrl: 'https://animesuge.cz/',
    logoUrl: 'https://animesuge.cz/favicon.ico',
    safeCdnDomains: ['cdn.animesuge.cz', 'static.animesuge.cz'],
    hideSelectors: ['header', '.site-header', 'footer', '.site-footer',
        '.popup', '.modal', '[class*="chat" i]'],
  ),
  _SiteRow(
    name: 'AnimeXin',
    homepageUrl: 'https://animexin.dev/',
    logoUrl: 'https://animexin.dev/wp-content/uploads/2026/01/cropped-New-Logo-e1768365053967-192x192.png',
    safeCdnDomains: ['cdn.animexin.dev', 'static.animexin.dev'],
    hideSelectors: ['.site-header', '#header', '.site-footer', '#footer',
        '.popup', '.modal', '[class*="chat" i]'],
  ),
  _SiteRow(
    name: 'AniZone',
    homepageUrl: 'https://anizone.to/',
    logoUrl: 'https://anizone.to/apple-touch-icon.png',
    safeCdnDomains: ['cdn.anizone.to', 'static.anizone.to'],
    hideSelectors: ['header', '.header', 'footer', '.footer', '.popup-overlay',
        '.modal', '[class*="chat" i]'],
  ),
  _SiteRow(
    name: 'AniDB',
    homepageUrl: 'https://anidb.app/home',
    logoUrl: 'https://anidb.app/favicon.ico',
    safeCdnDomains: ['cdn.anidb.app', 'static.anidb.app'],
    hideSelectors: ['.site-header', '#header', '.site-footer', '#footer',
        '.popup', '.modal', '[class*="chat" i]'],
  ),
  _SiteRow(
    name: 'AniKoto',
    homepageUrl: 'https://anikoto.cz/home',
    logoUrl: 'https://anikoto.cz/favicon.ico',
    safeCdnDomains: ['cdn.anikoto.cz', 'static.anikoto.cz'],
    hideSelectors: ['header', '.site-header', 'footer', '.site-footer',
        '.popup', '.modal', '[class*="chat" i]'],
  ),
  _SiteRow(
    name: 'AnimeNoSub',
    homepageUrl: 'https://animenosub.to/',
    logoUrl: 'https://i3.wp.com/animenosub.to/wp-content/uploads/2024/04/cropped-favicon-192x192.png',
    safeCdnDomains: ['cdn.animenosub.to', 'static.animenosub.to'],
    hideSelectors: ['header', '.header', 'footer', '.footer', '.popup-overlay',
        '.modal', '[class*="chat" i]'],
  ),

  // ── New general anime providers (from sites.md) ──
  _SiteRow(name: 'AniKotoTV', homepageUrl: 'https://anikototv.to/home',
      logoUrl: 'https://anikototv.to/favicon.ico',
      safeCdnDomains: ['cdn.anikototv.to', 'img.anikototv.to']),
  _SiteRow(name: 'Miruro', homepageUrl: 'https://www.miruro.to/',
      logoUrl: 'https://www.miruro.to/favicon.ico',
      safeCdnDomains: ['cdn.miruro.to', 'img.miruro.to']),
  _SiteRow(name: 'Mkissa', homepageUrl: 'https://mkissa.to/anime',
      logoUrl: 'https://mkissa.to/favicon.ico',
      safeCdnDomains: ['cdn.mkissa.to', 'img.mkissa.to']),
  _SiteRow(name: 'Senshi', homepageUrl: 'https://senshi.to/',
      logoUrl: 'https://senshi.to/favicon.ico',
      safeCdnDomains: ['cdn.senshi.to', 'img.senshi.to']),
  _SiteRow(name: 'AnimeUniqueStream', homepageUrl: 'https://anime.uniquestream.net/',
      logoUrl: 'https://anime.uniquestream.net/favicon.ico',
      safeCdnDomains: ['cdn.anime.uniquestream.net']),
  _SiteRow(name: 'KAA', homepageUrl: 'https://kaa.lt/',
      logoUrl: 'https://kaa.lt/favicon.ico',
      safeCdnDomains: ['cdn.kaa.lt', 'img.kaa.lt']),
  _SiteRow(name: 'AnimeNexus', homepageUrl: 'https://anime.nexus/',
      logoUrl: 'https://anime.nexus/favicon.ico',
      safeCdnDomains: ['cdn.anime.nexus', 'img.anime.nexus']),
  _SiteRow(name: 'Bilibili', homepageUrl: 'https://www.bilibili.tv/en/anime',
      logoUrl: 'https://www.bilibili.tv/favicon.ico',
      safeCdnDomains: ['i.bilibili.com', 'i0.hdslb.com', 'i1.hdslb.com']),
  _SiteRow(name: 'YouTube', homepageUrl: 'https://youtube.com/',
      logoUrl: 'https://www.youtube.com/s/desktop/f81c0da1/img/favicon.ico',
      safeCdnDomains: ['i.ytimg.com', 'ytimg.com', 'googlevideo.com']),
  _SiteRow(name: 'AniNeo', homepageUrl: 'https://anineko.to/',
      logoUrl: 'https://anineko.to/favicon.ico',
      safeCdnDomains: ['cdn.anineko.to', 'img.anineko.to']),
  _SiteRow(name: 'AniBD', homepageUrl: 'https://anibd.app/',
      logoUrl: 'https://anibd.app/favicon.ico',
      safeCdnDomains: ['cdn.anibd.app', 'img.anibd.app']),
  _SiteRow(name: 'AnimeOnsen', homepageUrl: 'https://www.animeonsen.xyz/',
      logoUrl: 'https://www.animeonsen.xyz/favicon.ico',
      safeCdnDomains: ['cdn.animeonsen.xyz']),
  _SiteRow(name: 'AniFy', homepageUrl: 'https://anify.to/',
      logoUrl: 'https://anify.to/favicon.ico',
      safeCdnDomains: ['cdn.anify.to', 'img.anify.to']),
  _SiteRow(name: 'AniSquawk', homepageUrl: 'https://anisnatch.to/home',
      logoUrl: 'https://anisnatch.to/favicon.ico',
      safeCdnDomains: ['cdn.anisnatch.to', 'img.anisnatch.to']),
  _SiteRow(name: 'AnimeHeaven', homepageUrl: 'https://animeheaven.me/',
      logoUrl: 'https://animeheaven.me/favicon.ico',
      safeCdnDomains: ['cdn.animeheaven.me', 'img.animeheaven.me']),
  _SiteRow(name: 'LunarX', homepageUrl: 'https://lunarx.to/anime',
      logoUrl: 'https://lunarx.to/favicon.ico',
      safeCdnDomains: ['cdn.lunarx.to', 'img.lunarx.to']),
  _SiteRow(name: 'AniPM', homepageUrl: 'https://ani.pm/',
      logoUrl: 'https://ani.pm/favicon.ico',
      safeCdnDomains: ['cdn.ani.pm', 'img.ani.pm']),
  _SiteRow(name: 'AniDap', homepageUrl: 'https://anidap.lol/home',
      logoUrl: 'https://anidap.lol/favicon.ico',
      safeCdnDomains: ['cdn.anidap.lol', 'img.anidap.lol']),
  _SiteRow(name: 'Just4Ani', homepageUrl: 'https://just4anime.online/',
      logoUrl: 'https://just4anime.online/favicon.ico',
      safeCdnDomains: ['cdn.just4anime.online']),
  _SiteRow(name: 'AniStream', homepageUrl: 'https://anistream.one/home',
      logoUrl: 'https://anistream.one/favicon.ico',
      safeCdnDomains: ['cdn.anistream.one', 'img.anistream.one']),
  _SiteRow(name: 'AnimeGG', homepageUrl: 'https://www.animegg.org/',
      logoUrl: 'https://www.animegg.org/favicon.ico',
      safeCdnDomains: ['cdn.animegg.org']),
  _SiteRow(name: 'XAnime', homepageUrl: 'https://xanime.me/',
      logoUrl: 'https://xanime.me/favicon.ico',
      safeCdnDomains: ['cdn.xanime.me', 'img.xanime.me']),
  _SiteRow(name: '2DHive', homepageUrl: 'https://2dhive.com/',
      logoUrl: 'https://2dhive.com/favicon.ico',
      safeCdnDomains: ['cdn.2dhive.com']),
  _SiteRow(name: 'AniWorld', homepageUrl: 'https://aniworld.to/',
      logoUrl: 'https://aniworld.to/favicon.ico',
      safeCdnDomains: ['cdn.aniworld.to', 'img.aniworld.to']),
  _SiteRow(name: 'AniChan', homepageUrl: 'https://anichan.net/',
      logoUrl: 'https://anichan.net/favicon.ico',
      safeCdnDomains: ['cdn.anichan.net']),
  _SiteRow(name: 'AnimeTVSlash', homepageUrl: 'https://www.animotvslash.org/',
      logoUrl: 'https://www.animotvslash.org/favicon.ico',
      safeCdnDomains: ['cdn.animotvslash.org']),
  _SiteRow(name: 'HiDive', homepageUrl: 'https://www.hidive.com/',
      logoUrl: 'https://www.hidive.com/favicon.ico',
      safeCdnDomains: ['cdn.hidive.com', 'rivedrm.blob.core.windows.net']),
  _SiteRow(name: 'AniKuro', homepageUrl: 'https://anikuro.ru/',
      logoUrl: 'https://anikuro.ru/favicon.ico',
      safeCdnDomains: ['cdn.anikuro.ru']),
  _SiteRow(name: 'BetterMelon', homepageUrl: 'https://bettermelon.ru/',
      logoUrl: 'https://bettermelon.ru/favicon.ico',
      safeCdnDomains: ['cdn.bettermelon.ru']),
  _SiteRow(name: 'KissKH', homepageUrl: 'https://kisskh.co/',
      logoUrl: 'https://kisskh.co/favicon.ico',
      safeCdnDomains: ['cdn.kisskh.co', 'img.kisskh.co']),
  _SiteRow(name: 'HiAnimes', homepageUrl: 'https://hianimes.se/home',
      logoUrl: 'https://hianimes.se/favicon.ico',
      safeCdnDomains: ['cdn.hianimes.se', 'img.hianimes.se']),
  _SiteRow(name: 'AniKaio', homepageUrl: 'https://animekai.ro/',
      logoUrl: 'https://animekai.ro/favicon.ico',
      safeCdnDomains: ['cdn.animekai.ro', 'img.animekai.ro']),
  _SiteRow(name: 'FireAni', homepageUrl: 'https://fireani.me/',
      logoUrl: 'https://fireani.me/favicon.ico',
      safeCdnDomains: ['cdn.fireani.me']),
  _SiteRow(name: 'AnimeLoads', homepageUrl: 'https://www.anime-loads.org/',
      logoUrl: 'https://www.anime-loads.org/favicon.ico',
      safeCdnDomains: ['cdn.anime-loads.org', 'img.anime-loads.org']),
  _SiteRow(name: 'WcoStream', homepageUrl: 'https://www.wcostream.tv/',
      logoUrl: 'https://www.wcostream.tv/favicon.ico',
      safeCdnDomains: ['cdn.wcostream.tv', 'trollscastle.wcostream.tv',
          'stream.wcostream.tv']),
  _SiteRow(name: 'KimoITV', homepageUrl: 'https://kimoitv.com/',
      logoUrl: 'https://kimoitv.com/favicon.ico',
      safeCdnDomains: ['cdn.kimoitv.com']),
  _SiteRow(name: 'OtakuStreamers', homepageUrl: 'https://otaku-streamers.com/',
      logoUrl: 'https://otaku-streamers.com/favicon.ico',
      safeCdnDomains: ['cdn.otaku-streamers.com', 'img.otaku-streamers.com']),
  _SiteRow(name: 'AV1Please', homepageUrl: 'https://av1please.com/',
      logoUrl: 'https://av1please.com/favicon.ico',
      safeCdnDomains: ['cdn.av1please.com', 'img.av1please.com']),
  _SiteRow(name: 'KuroAni', homepageUrl: 'https://kuroanime.lol/',
      logoUrl: 'https://kuroanime.lol/favicon.ico',
      safeCdnDomains: ['cdn.kuroanime.lol', 'img.kuroanime.lol']),
  _SiteRow(name: '4AniMo', homepageUrl: 'https://4animo.xyz/home',
      logoUrl: 'https://4animo.xyz/favicon.ico',
      safeCdnDomains: ['cdn.4animo.xyz']),
  _SiteRow(name: 'AniLight', homepageUrl: 'https://anilight.live/',
      logoUrl: 'https://anilight.live/favicon.ico',
      safeCdnDomains: ['cdn.anilight.live', 'img.anilight.live']),
  _SiteRow(name: 'MegaAni', homepageUrl: 'https://meguanime.com/',
      logoUrl: 'https://meguanime.com/favicon.ico',
      safeCdnDomains: ['cdn.meguanime.com', 'img.meguanime.com']),
  _SiteRow(name: 'Otakutsu', homepageUrl: 'https://otakutsu.cc/',
      logoUrl: 'https://otakutsu.cc/favicon.ico',
      safeCdnDomains: ['cdn.otakutsu.cc', 'img.otakutsu.cc']),
  _SiteRow(name: 'JustAni', homepageUrl: 'https://www.justanime.to/',
      logoUrl: 'https://www.justanime.to/favicon.ico',
      safeCdnDomains: ['cdn.justanime.to', 'img.justanime.to']),
  _SiteRow(name: 'LunaStream', homepageUrl: 'https://luna-stream.me/',
      logoUrl: 'https://luna-stream.me/favicon.ico',
      safeCdnDomains: ['cdn.luna-stream.me', 'img.luna-stream.me']),
  _SiteRow(name: 'AniXo', homepageUrl: 'https://anixo.online/',
      logoUrl: 'https://anixo.online/favicon.ico',
      safeCdnDomains: ['cdn.anixo.online', 'img.anixo.online']),
  _SiteRow(name: 'AniYubi', homepageUrl: 'https://animeyubi.com/',
      logoUrl: 'https://animeyubi.com/favicon.ico',
      safeCdnDomains: ['cdn.animeyubi.com', 'img.animeyubi.com']),
  _SiteRow(name: 'Kazora', homepageUrl: 'https://kazora.cc/',
      logoUrl: 'https://kazora.cc/favicon.ico',
      safeCdnDomains: ['cdn.kazora.cc', 'img.kazora.cc']),
  _SiteRow(name: 'YumeZone', homepageUrl: 'https://yumezone.live/',
      logoUrl: 'https://yumezone.live/favicon.ico',
      safeCdnDomains: ['cdn.yumezone.live', 'img.yumezone.live']),
  _SiteRow(name: 'Itachi', homepageUrl: 'https://itachi.tv/',
      logoUrl: 'https://itachi.tv/favicon.ico',
      safeCdnDomains: ['cdn.itachi.tv', 'img.itachi.tv']),
  _SiteRow(name: 'Kaorii', homepageUrl: 'https://kaorii.app/',
      logoUrl: 'https://kaorii.app/favicon.ico',
      safeCdnDomains: ['cdn.kaorii.app', 'img.kaorii.app']),
  _SiteRow(name: 'LuffyTV', homepageUrl: 'https://luffytv.live/',
      logoUrl: 'https://luffytv.live/favicon.ico',
      safeCdnDomains: ['cdn.luffytv.live', 'img.luffytv.live']),
  _SiteRow(name: 'Kyren', homepageUrl: 'https://kyren.moe/',
      logoUrl: 'https://kyren.moe/favicon.ico',
      safeCdnDomains: ['cdn.kyren.moe', 'img.kyren.moe']),
  _SiteRow(name: 'AniTok', homepageUrl: 'https://animelok.live/',
      logoUrl: 'https://animelok.live/favicon.ico',
      safeCdnDomains: ['cdn.animelok.live', 'img.animelok.live']),
  _SiteRow(name: 'PimpAni', homepageUrl: 'https://pimpanime.nl/',
      logoUrl: 'https://pimpanime.nl/favicon.ico',
      safeCdnDomains: ['cdn.pimpanime.nl', 'img.pimpanime.nl']),
  _SiteRow(name: 'Zenkai', homepageUrl: 'https://zenkai.to/home',
      logoUrl: 'https://zenkai.to/favicon.ico',
      safeCdnDomains: ['cdn.zenkai.to', 'img.zenkai.to']),
  _SiteRow(name: 'AniWatchTV', homepageUrl: 'https://aniwatchtv.com.ro/',
      logoUrl: 'https://aniwatchtv.com.ro/favicon.ico',
      safeCdnDomains: ['cdn.aniwatchtv.com.ro', 'img.aniwatchtv.com.ro']),
  _SiteRow(name: 'OceanVeil', homepageUrl: 'https://oceanveil.net/',
      logoUrl: 'https://oceanveil.net/favicon.ico',
      safeCdnDomains: ['cdn.oceanveil.net', 'img.oceanveil.net']),
  _SiteRow(name: 'RetroCrush', homepageUrl: 'https://www.retrocrush.tv/',
      logoUrl: 'https://www.retrocrush.tv/favicon.ico',
      safeCdnDomains: ['cdn.retrocrush.tv', 'img.retrocrush.tv']),
  _SiteRow(name: 'Yomi', homepageUrl: 'https://yomi.to/',
      logoUrl: 'https://yomi.to/favicon.ico',
      safeCdnDomains: ['cdn.yomi.to', 'img.yomi.to']),
  _SiteRow(name: 'AniSil', homepageUrl: 'https://animesilo.cc/anime',
      logoUrl: 'https://animesilo.cc/favicon.ico',
      safeCdnDomains: ['cdn.animesilo.cc', 'img.animesilo.cc']),
  _SiteRow(name: 'NekoWatch', homepageUrl: 'https://nekowatch.xyz/',
      logoUrl: 'https://nekowatch.xyz/favicon.ico',
      safeCdnDomains: ['cdn.nekowatch.xyz', 'img.nekowatch.xyz']),
  _SiteRow(name: 'WatchAniZ', homepageUrl: 'https://watchanimez.me/',
      logoUrl: 'https://watchanimez.me/favicon.ico',
      safeCdnDomains: ['cdn.watchanimez.me', 'img.watchanimez.me']),
  _SiteRow(name: 'AniClipse', homepageUrl: 'https://aniclipse.com/',
      logoUrl: 'https://aniclipse.com/favicon.ico',
      safeCdnDomains: ['cdn.aniclipse.com', 'img.aniclipse.com']),
  _SiteRow(name: 'AniKura', homepageUrl: 'https://anikura.club/',
      logoUrl: 'https://anikura.club/favicon.ico',
      safeCdnDomains: ['cdn.anikura.club', 'img.anikura.club']),
  _SiteRow(name: 'AniTVPlus', homepageUrl: 'https://animetvplus.xyz/',
      logoUrl: 'https://animetvplus.xyz/favicon.ico',
      safeCdnDomains: ['cdn.animetvplus.xyz', 'img.animetvplus.xyz']),
  _SiteRow(name: 'OniAni', homepageUrl: 'https://onianime.eu/home',
      logoUrl: 'https://onianime.eu/favicon.ico',
      safeCdnDomains: ['cdn.onianime.eu', 'img.onianime.eu']),
  _SiteRow(name: 'AniGers', homepageUrl: 'https://animegers.com/',
      logoUrl: 'https://animegers.com/favicon.ico',
      safeCdnDomains: ['cdn.animegers.com', 'img.animegers.com']),
  _SiteRow(name: 'AniDex', homepageUrl: 'https://animedex.fun/',
      logoUrl: 'https://animedex.fun/favicon.ico',
      safeCdnDomains: ['cdn.animedex.fun', 'img.animedex.fun']),
  _SiteRow(name: 'Last1234', homepageUrl: 'https://last1234.fun/',
      logoUrl: 'https://last1234.fun/favicon.ico',
      safeCdnDomains: ['cdn.last1234.fun', 'img.last1234.fun']),
  _SiteRow(name: 'KawaiiAni', homepageUrl: 'https://kawaii-anime.com/',
      logoUrl: 'https://kawaii-anime.com/favicon.ico',
      safeCdnDomains: ['cdn.kawaii-anime.com', 'img.kawaii-anime.com']),
  _SiteRow(name: 'StreamEx', homepageUrl: 'https://streamex.sh/anime',
      logoUrl: 'https://streamex.sh/favicon.ico',
      safeCdnDomains: ['cdn.streamex.sh', 'img.streamex.sh']),
  _SiteRow(name: 'SanAni', homepageUrl: 'https://sankanime.web.id/',
      logoUrl: 'https://sankanime.web.id/favicon.ico',
      safeCdnDomains: ['cdn.sankanime.web.id', 'img.sankanime.web.id']),
  _SiteRow(name: 'AniWaveSE', homepageUrl: 'https://aniwave.com.se/',
      logoUrl: 'https://aniwave.com.se/favicon.ico',
      safeCdnDomains: ['cdn.aniwave.com.se', 'img.aniwave.com.se']),
  _SiteRow(name: 'RamenFlix', homepageUrl: 'https://ramenflix.com/home',
      logoUrl: 'https://ramenflix.com/favicon.ico',
      safeCdnDomains: ['cdn.ramenflix.com', 'img.ramenflix.com']),
  _SiteRow(name: 'Hulu', homepageUrl: 'https://www.hulu.com/hub/anime',
      logoUrl: 'https://www.hulu.com/favicon.ico',
      safeCdnDomains: ['cdn.hulu.com', 'assets.hulu.com']),
  _SiteRow(name: 'Enma', homepageUrl: 'https://www.enma.lol/',
      logoUrl: 'https://www.enma.lol/favicon.ico',
      safeCdnDomains: ['cdn.enma.lol', 'img.enma.lol']),
  _SiteRow(name: 'AnimeDunya', homepageUrl: 'https://anime-dunya.com/',
      logoUrl: 'https://anime-dunya.com/favicon.ico',
      safeCdnDomains: ['cdn.anime-dunya.com', 'img.anime-dunya.com']),
  _SiteRow(name: 'AniMixPlay', homepageUrl: 'https://animixplay.fun/',
      logoUrl: 'https://animixplay.fun/favicon.ico',
      safeCdnDomains: ['cdn.animixplay.fun', 'img.animixplay.fun']),
  _SiteRow(name: 'WatchAniWorld', homepageUrl: 'https://watchanimeworld.one/',
      logoUrl: 'https://watchanimeworld.one/favicon.ico',
      safeCdnDomains: ['cdn.watchanimeworld.one', 'img.watchanimeworld.one']),
  _SiteRow(name: 'Ani Dekho', homepageUrl: 'https://animedekho.app/home',
      logoUrl: 'https://animedekho.app/favicon.ico',
      safeCdnDomains: ['cdn.animedekho.app', 'img.animedekho.app']),

  // ── Mature / 18+ content (from existing set) ──
  _SiteRow(
    name: 'Rule34Video',
    homepageUrl: 'https://rule34video.com/',
    logoUrl: 'https://rule34video.com/apple-touch-icon.png',
    safeCdnDomains: ['cdn.rule34video.com', 'img.rule34video.com'],
    hideSelectors: ['.site-header', '#header', '.site-footer', '#footer',
        '.banner', '.popup', '.modal'],
    mature: true,
  ),
  _SiteRow(
    name: 'HentaiTV',
    homepageUrl: 'https://hentai.tv/',
    logoUrl: 'https://hentai.tv/apple-icon.png?apple-icon.0c08tjjgl86o0.png',
    safeCdnDomains: ['cdn.hentai.tv', 'img.hentai.tv', 'stream.hentai.tv'],
    hideSelectors: ['header', '.header', 'footer', '.footer', '.nav',
        '.ad-placeholder', '.popup'],
    mature: true,
  ),
  _SiteRow(
    name: 'HentaiCity',
    homepageUrl: 'https://www.hentaicity.com/',
    logoUrl: 'https://www.hentaicity.com/apple-touch-icon.png',
    safeCdnDomains: ['cdn.hentaicity.com', 'static.hentaicity.com'],
    hideSelectors: ['.header', '#header', '.footer', '#footer', '.navbar',
        '.ads', '.popup-overlay'],
    mature: true,
  ),
  _SiteRow(
    name: 'UnderHentai',
    homepageUrl: 'https://www.underhentai.net/',
    logoUrl: 'https://static.underhentai.net/themes/undernet-bs3/icons/xapple-touch-icon.png.pagespeed.ic.EqN0jX-NzE.webp',
    safeCdnDomains: ['cdn.underhentai.net', 'img.underhentai.net'],
    hideSelectors: ['.site-header', '#header', '.site-footer', '#footer',
        '.top-bar', '.popup', '.modal'],
    mature: true,
  ),
  _SiteRow(
    name: 'OppaiStream',
    homepageUrl: 'https://oppai.stream/',
    logoUrl: 'https://oppai.stream/assets/logo/apple-touch-icon.png',
    safeCdnDomains: ['cdn.oppai.stream', 'media.oppai.stream'],
    hideSelectors: ['header', '.header', 'footer', '.footer', '.nav-wrap',
        '.banner-ad', '.popup'],
    mature: true,
  ),
  _SiteRow(
    name: 'HentaiMoon',
    homepageUrl: 'https://hentai-moon.com/discover/',
    logoUrl: 'https://hentai-moon.com/favicon.ico',
    safeCdnDomains: ['cdn.hentai-moon.com', 'img.hentai-moon.com'],
    hideSelectors: ['.site-header', '#header', '.site-footer', '#footer',
        '.discover-ad', '.popup', '.modal'],
    mature: true,
  ),

  // ── New hentai / 18+ providers (from user paste) ────────────────
  _SiteRow(name: 'HStream', homepageUrl: 'https://hstream.moe/',
      mature: true),
  _SiteRow(name: 'HentaiHaven', homepageUrl: 'https://hentaihaven.xxx/',
      mature: true),
  _SiteRow(name: 'Hanime', homepageUrl: 'https://hanime.tv/',
      mature: true),
  _SiteRow(name: 'HAHO', homepageUrl: 'https://haho.moe/',
      mature: true),
  _SiteRow(name: 'Hentaiverse', homepageUrl: 'https://hentaiverse.com/',
      mature: true),
  _SiteRow(name: 'HentaiSH', homepageUrl: 'https://hentai.sh/',
      mature: true),
  _SiteRow(name: 'HentaiOcean', homepageUrl: 'https://hentaiocean.com/',
      mature: true),
  _SiteRow(name: 'HentaiDB', homepageUrl: 'https://hentaidb.xyz/',
      mature: true),
  _SiteRow(name: 'ZhenTube', homepageUrl: 'https://zhentube.com/',
      mature: true),
  _SiteRow(name: 'WatchHentai', homepageUrl: 'https://watchhentai.net/',
      mature: true),
  _SiteRow(name: 'HentaiHT', homepageUrl: 'https://hentai.ht/',
      mature: true),
  _SiteRow(name: 'HentaiStream', homepageUrl: 'https://tube.hentaistream.com/',
      safeCdnDomains: ['tube.hentaistream.com', 'cdn.hentaistream.com'],
      mature: true),
  _SiteRow(name: 'HentaiPlay', homepageUrl: 'https://hentaiplay.net/',
      mature: true),
  _SiteRow(name: 'OnlyHentaiStuff', homepageUrl: 'https://www.onlyhentaistuff.com/',
      mature: true),
  _SiteRow(name: 'Hanime1', homepageUrl: 'https://hanime1.me/',
      mature: true),
  _SiteRow(name: 'HentaiWorld', homepageUrl: 'https://hentaiworld.tv/',
      mature: true),
  _SiteRow(name: 'MyHentaiMovie', homepageUrl: 'https://myhentaimovie.com/',
      mature: true),
  _SiteRow(name: 'AkiH', homepageUrl: 'https://aki-h.com/',
      mature: true),
  _SiteRow(name: 'Hentaini', homepageUrl: 'https://hentaini.com/',
      mature: true),
  _SiteRow(name: 'Hentai2W', homepageUrl: 'https://hentai2w.com/',
      mature: true),
  _SiteRow(name: 'Hentaigasm', homepageUrl: 'https://hentaigasm.com/',
      mature: true),
  _SiteRow(name: 'HentaiMama', homepageUrl: 'https://hentaimama.io/',
      mature: true),
  _SiteRow(name: 'HmvMania', homepageUrl: 'https://hmvmania.com/',
      mature: true),
  _SiteRow(name: 'Hentai0', homepageUrl: 'https://hentai0.com/',
      mature: true),
  _SiteRow(name: 'Iwara', homepageUrl: 'https://www.iwara.tv/',
      safeCdnDomains: ['cdn.iwara.tv', 'files.iwara.tv'],
      mature: true),
  _SiteRow(name: 'HentaiFox', homepageUrl: 'https://hentaifox.tv/',
      mature: true),
  _SiteRow(name: 'HentaiBros', homepageUrl: 'https://hentibros.net/',
      mature: true),
  _SiteRow(name: 'Hentaiser', homepageUrl: 'https://app.hentaiser.com/animes/hot',
      mature: true),
  _SiteRow(name: 'HentaiFor', homepageUrl: 'https://hentai-for.net/',
      mature: true),
  _SiteRow(name: 'KissHentaiZ', homepageUrl: 'https://kisshentaiz.com/',
      mature: true),
  _SiteRow(name: 'HentaiVideoWorld', homepageUrl: 'https://hentaivideoworld.com/',
      mature: true),
  _SiteRow(name: 'EsHentai', homepageUrl: 'https://eshentai.tv/en',
      mature: true),
  _SiteRow(name: 'XAnimePorn', homepageUrl: 'https://www.xanimeporn.com/',
      mature: true),
  _SiteRow(name: 'VidHentai', homepageUrl: 'https://vidhentai.com/',
      mature: true),
  _SiteRow(name: 'HentaiFreak', homepageUrl: 'https://hentaifreak.org/',
      mature: true),
  _SiteRow(name: 'MuchoHentai', homepageUrl: 'https://muchohentai.com/',
      mature: true),
  _SiteRow(name: 'HentaiCloud', homepageUrl: 'https://www.hentaicloud.com/',
      mature: true),
  _SiteRow(name: 'HentaiSea', homepageUrl: 'https://hentaisea.com/',
      mature: true),
];

/// The default set of streaming providers shipped with the app. Generated
/// from [_allSites] so adding an entry to that table is all it takes.
final List<AnimeSiteConfig> defaultSites =
    _allSites.map((row) => row.toConfig()).toList(growable: false);

/// Only the mature/18+ entries, for grouped display or filtering.
final List<AnimeSiteConfig> matureSites =
    _allSites.where((r) => r.mature).map((r) => r.toConfig()).toList();

/// General (non-mature) streaming providers.
final List<AnimeSiteConfig> generalSites =
    _allSites.where((r) => !r.mature).map((r) => r.toConfig()).toList();

/// The example template configs from [site_config.dart], re-exported for
/// convenience in the add-site dialog.
const List<AnimeSiteConfig> templateSitesExported = templateSites;
